<?php $pageTitle='Blogs'; require_once __DIR__.'/includes/header.php';
$pdo=db(); $search=trim($_GET['q']??''); $status=$_GET['status']??''; $category=(int)($_GET['category']??0);
$sql="SELECT b.*,c.name category_name FROM blogs b JOIN blog_categories c ON c.id=b.category_id WHERE 1"; $params=[];
if($search!==''){ $sql.=' AND (b.title LIKE ? OR b.slug LIKE ?)'; $params[]='%'.$search.'%'; $params[]='%'.$search.'%'; }
if(in_array($status,['draft','published'],true)){ $sql.=' AND b.status=?'; $params[]=$status; }
if($category>0){$sql.=' AND b.category_id=?';$params[]=$category;}
$sql.=' ORDER BY b.publish_date DESC,b.id DESC'; $st=$pdo->prepare($sql);$st->execute($params);$blogs=$st->fetchAll(); $cats=$pdo->query("SELECT * FROM blog_categories ORDER BY name")->fetchAll();
?>
<div class="panel"><div class="filter-bar"><form class="row g-2" method="get"><div class="col-lg-5"><input class="form-control" name="q" placeholder="Search blogs..." value="<?=e($search)?>"></div><div class="col-lg-3"><select class="form-select" name="category"><option value="0">All categories</option><?php foreach($cats as $c): ?><option value="<?=$c['id']?>" <?=$category===$c['id']?'selected':''?>><?=e($c['name'])?></option><?php endforeach; ?></select></div><div class="col-lg-2"><select class="form-select" name="status"><option value="">All status</option><option value="published" <?=$status==='published'?'selected':''?>>Published</option><option value="draft" <?=$status==='draft'?'selected':''?>>Draft</option></select></div><div class="col-lg-2"><button class="btn btn-primary w-100">Filter</button></div></form></div><div class="panel-head"><div><h3>All Blogs</h3><p><?=count($blogs)?> result(s)</p></div><a href="blog-form.php" class="btn btn-primary"><i class="fa-solid fa-plus me-1"></i>Add Blog</a></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th style="width:42%">Blog</th><th>Category</th><th>Published</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody><?php foreach($blogs as $b): ?><tr><td><div class="blog-row"><img src="../<?=e($b['featured_image'] ?: 'assets/logo.png')?>" alt=""><div><strong><?=e($b['title'])?></strong><small><?=e($b['author'])?></small></div></div></td><td><span class="category-pill"><?=e($b['category_name'])?></span></td><td><?=date('d M Y',strtotime($b['publish_date']))?></td><td><span class="status <?=e($b['status'])?>"><?=ucfirst(e($b['status']))?></span></td><td class="text-end"><a class="icon-btn" href="../blog-detail.php?slug=<?=urlencode($b['slug'])?>" target="_blank" title="View"><i class="fa-regular fa-eye"></i></a><a class="icon-btn" href="blog-form.php?id=<?=$b['id']?>" title="Edit"><i class="fa-solid fa-pen"></i></a><a class="icon-btn danger" href="blog-delete.php?id=<?=$b['id']?>&csrf=<?=e(csrf_token())?>" onclick="return confirm('Delete this blog?')" title="Delete"><i class="fa-solid fa-trash"></i></a></td></tr><?php endforeach; if(!$blogs): ?><tr><td colspan="5" class="text-center py-5">No blogs found.</td></tr><?php endif; ?></tbody></table></div></div>
<?php require_once __DIR__.'/includes/footer.php'; ?>
